---
abstract: 'build a custom file by running an external command'
author:
  - 'Stirling Westrup <swestrup@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-BuildFile
requires:
  Data::Dumper: 0
  Dist::Zilla::Role::AfterBuild: 0
  Dist::Zilla::Role::BeforeBuild: 0
  IPC::Run3: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Types::Path::Class: 0
  Text::Template: 0
  namespace::autoclean: 0
  perl: 5.006
version: 0.04
